export function createRuntimeState() {
  return {
    workerProcess: null,
    workerLastLog: '',
    workerStartedAt: '',
    lossOrderMonitorTimer: null,
    lossOrderMonitorRunning: false,
    matchingSyncTimer: null,
    matchingSyncRunning: false,
    opsPollTimer: null,
    opsPollRunning: false,
    opsPollLastRunAt: null,
    opsPollLastRunOk: null,
    opsPollLastError: null,
    opsPollLastReport: null,
    stockAutoSyncTimer: null,
    stockAutoSyncRunning: false,
    stockAutoSyncLastRunAt: null,
    stockAutoSyncLastRunOk: null,
    stockAutoSyncLastError: null,
    stockAutoSyncLastReport: null,
    opsActivityEvents: [],
    lastCacheSyncAt: 0,
    lastOrdersFetchAt: 0,
    getirLiveSyncAt: 0,
    getirLiveSyncSummary: null,
    orderChannelProductSyncAt: {},
    ordersCache: {},
    channelOrdersCache: {}
  };
}
